<?php
declare(strict_types=1);require __DIR__.'/../config.php';$u=loggedUser();if(!$u||$u['role']!=='employee')jsonResponse(false,'Employee access required.',[],403);requirePost();requireCsrf();$pdo=db();$action=(string)($_POST['action']??'');
function geoDistance(float $lat1,float $lon1,float $lat2,float $lon2):float{$r=6371000;$p1=deg2rad($lat1);$p2=deg2rad($lat2);$dp=deg2rad($lat2-$lat1);$dl=deg2rad($lon2-$lon1);$a=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return 2*$r*asin(min(1,sqrt($a)));}
if($action==='mark-attendance'){
 $lat=filter_var($_POST['latitude']??null,FILTER_VALIDATE_FLOAT);$lng=filter_var($_POST['longitude']??null,FILTER_VALIDATE_FLOAT);$alt=$_POST['altitude']!==''?(float)$_POST['altitude']:null;$acc=$_POST['accuracy']!==''?(float)$_POST['accuracy']:null;if($lat===false||$lng===false)jsonResponse(false,'Location could not be read. Please enable GPS and try again.',[],422);
 $office=$pdo->query('SELECT * FROM office_settings WHERE id=1')->fetch();if(!$office||$office['latitude']===null||$office['longitude']===null)jsonResponse(false,'Attendance location is not configured by admin.',[],422);$distance=geoDistance((float)$lat,(float)$lng,(float)$office['latitude'],(float)$office['longitude']);$date=date('Y-m-d');$q=$pdo->prepare('SELECT * FROM attendance WHERE employee_id=? AND attendance_date=? LIMIT 1');$q->execute([(int)$u['id'],$date]);$existing=$q->fetch();$attempts=$existing?(int)$existing['attempts']+1:1;
 if($distance <= (float)$office['radius_meters']){$s=$pdo->prepare("INSERT INTO attendance(employee_id,attendance_date,marked_at,latitude,longitude,altitude,accuracy,distance_meters,method,status,attempts,note) VALUES(?,?,NOW(),?,?,?,?,?,'employee_gps','present',?,?) ON DUPLICATE KEY UPDATE marked_at=NOW(),latitude=VALUES(latitude),longitude=VALUES(longitude),altitude=VALUES(altitude),accuracy=VALUES(accuracy),distance_meters=VALUES(distance_meters),method='employee_gps',status='present',attempts=VALUES(attempts),note=VALUES(note)");$s->execute([(int)$u['id'],$date,$lat,$lng,$alt,$acc,$distance,$attempts,'Inside office geofence']);jsonResponse(true,'Attendance marked present.', ['status'=>'present','distance'=>$distance,'radius'=>$office['radius_meters']]);}
 if($existing&&$existing['status']==='rejected')jsonResponse(false,'Today attendance has already been rejected.',[],422);
 $status=$attempts>=4?'rejected':'pending';$note=$status==='rejected'?'Location remained outside the allowed radius after 4 attempts.':'Outside the allowed radius. You can retry.';$s=$pdo->prepare("INSERT INTO attendance(employee_id,attendance_date,marked_at,latitude,longitude,altitude,accuracy,distance_meters,method,status,attempts,note) VALUES(?,?,NOW(),?,?,?,?,?,'employee_gps',?,?,?) ON DUPLICATE KEY UPDATE marked_at=NOW(),latitude=VALUES(latitude),longitude=VALUES(longitude),altitude=VALUES(altitude),accuracy=VALUES(accuracy),distance_meters=VALUES(distance_meters),method='employee_gps',status=VALUES(status),attempts=VALUES(attempts),note=VALUES(note)");$s->execute([(int)$u['id'],$date,$lat,$lng,$alt,$acc,$distance,$status,$attempts,$note]);jsonResponse($status==='rejected'?false:true,$status==='rejected'?'Attendance rejected after 4 attempts.':'You are outside the attendance radius. Retry from the office.', ['status'=>$status,'distance'=>$distance,'radius'=>$office['radius_meters'],'attempts'=>$attempts], $status==='rejected'?422:200);
}
if($action==='assignment-status'){$id=(int)$_POST['id'];$status=$_POST['status']??'';if(!in_array($status,['accepted','in_progress','completed'],true))jsonResponse(false,'Invalid status.',[],422);$q=$pdo->prepare('UPDATE employee_assignments SET status=?,started_at=CASE WHEN ?="in_progress" AND started_at IS NULL THEN NOW() ELSE started_at END,completed_at=CASE WHEN ?="completed" THEN NOW() ELSE completed_at END WHERE id=? AND employee_id=? AND status NOT IN ("cancelled")');$q->execute([$status,$status,$status,$id,(int)$u['id']]);jsonResponse($q->rowCount()>0,'Assignment updated.');}
jsonResponse(false,'Unknown action.',[],400);
