<?php
require_once __DIR__.'/config.php';
$pdo=db();
$row=$pdo->query("SELECT setting_key,value FROM site_settings WHERE setting_key IN ('maintenance_title','maintenance_message')")->fetchAll();
$settings=[]; foreach($row as $r)$settings[$r['setting_key']]=$r['value'];
$title=$settings['maintenance_title']??'We are upgrading Swarnim Groups';
$message=$settings['maintenance_message']??'Our website is temporarily unavailable while we improve your shopping experience.';
?><!doctype html><html lang="en"><head><link rel="icon" type="image/png" sizes="256x256" href="data/favicon.png"><link rel="apple-touch-icon" href="data/favicon.png"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> — Swarnim Groups</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 20% 20%,rgba(244,197,66,.14),transparent 30%),radial-gradient(circle at 80% 80%,rgba(89,137,255,.14),transparent 30%),#070a10;color:#fff;font-family:Inter,system-ui,sans-serif}.wrap{width:min(760px,92%);text-align:center;padding:56px 34px;border:1px solid rgba(255,255,255,.1);border-radius:32px;background:rgba(15,21,31,.8);backdrop-filter:blur(22px);box-shadow:0 40px 120px rgba(0,0,0,.5);animation:up .7s ease}.logo{width:86px;height:86px;object-fit:contain;margin-bottom:25px;filter:drop-shadow(0 15px 25px rgba(0,0,0,.35))}h1{font-size:clamp(32px,6vw,58px);margin:0 0 14px;letter-spacing:-.04em}p{color:#aeb8c7;line-height:1.8;font-size:16px;max-width:580px;margin:0 auto 28px}.loader{width:180px;height:5px;margin:auto;background:#1b2431;border-radius:20px;overflow:hidden}.loader i{display:block;width:45%;height:100%;background:linear-gradient(90deg,#f4c542,#fff0a8);animation:load 1.6s infinite}@keyframes up{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}@keyframes load{0%{transform:translateX(-100%)}100%{transform:translateX(450%)}}
</style></head><body><main class="wrap"><img class="logo" src="data/Swarnim Logo.png" alt="Swarnim Groups"><h1><?=htmlspecialchars($title)?></h1><p><?=nl2br(htmlspecialchars($message))?></p><div class="loader"><i></i></div></main></body></html>